USE master
GO

CREATE MASTER KEY ENCRYPTION BY PASSWORD = ‘StrongPassword’
GO

CREATE CERTIFICATE MyCert WITH SUBJECT = ‘Certificado DEK’
GO

USE alunos
GO

CREATE DATABASE ENCRYPTION KEY WITH ALGORITHM = AES_128

ENCRYPTION BY SERVER CERTIFICATE MyCert;
GO

ALTER DATABASE alunos SET ENCRYPTION ON;
GO
